export type CatalogPaper = {
  id: string;
  shortTitle: string;
  title: string;
  year: number;
  relation: string;
  coupling: string;
  substrate: string;
  status: '元数据已核验' | '已精读';
  paperUrl: string;
  detailUrl?: string;
};

export type CatalogGroup = {
  id: string;
  index: string;
  title: string;
  description: string;
  papers: CatalogPaper[];
};

export const catalogGroups: CatalogGroup[] = [
  {
    id: 'foundations',
    index: '01',
    title: '世界模型与控制基础',
    description: '理解像素预测、潜在动力学、想象学习与模型预测控制如何影响行动。',
    papers: [
      {
        id: '1610.00696',
        shortTitle: 'Deep Visual Foresight',
        title: 'Deep Visual Foresight for Planning Robot Motion',
        year: 2016,
        relation: 'WAM 前置脉络',
        coupling: '级联规划',
        substrate: '像素未来',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/1610.00696',
      },
      {
        id: '1803.10122',
        shortTitle: 'World Models',
        title: 'World Models',
        year: 2018,
        relation: '策略学习世界模型',
        coupling: '模块化',
        substrate: '潜在状态',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/1803.10122',
      },
      {
        id: '1811.04551',
        shortTitle: 'PlaNet',
        title: 'Learning Latent Dynamics for Planning from Pixels',
        year: 2018,
        relation: '策略学习世界模型',
        coupling: '模型上规划',
        substrate: '潜在状态',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/1811.04551',
      },
      {
        id: '1911.08265',
        shortTitle: 'MuZero',
        title: 'Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model',
        year: 2019,
        relation: '策略学习世界模型',
        coupling: '模型上规划',
        substrate: '任务相关潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/1911.08265',
      },
      {
        id: '1912.01603',
        shortTitle: 'Dreamer',
        title: 'Dream to Control: Learning Behaviors by Latent Imagination',
        year: 2019,
        relation: '策略学习世界模型',
        coupling: '模型内策略学习',
        substrate: '潜在状态',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/1912.01603',
      },
      {
        id: '2203.04955',
        shortTitle: 'TD-MPC',
        title: 'Temporal Difference Learning for Model Predictive Control',
        year: 2022,
        relation: '策略学习世界模型',
        coupling: '模型上规划',
        substrate: '任务导向潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2203.04955',
      },
      {
        id: '2301.04104',
        shortTitle: 'DreamerV3',
        title: 'Mastering Diverse Domains through World Models',
        year: 2023,
        relation: '策略学习世界模型',
        coupling: '模型内策略学习',
        substrate: '潜在状态',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2301.04104',
      },
    ],
  },
  {
    id: 'cascaded',
    index: '02',
    title: '级联式视频规划与动作解码',
    description: '先预测视觉未来或中间几何表征，再把它转换为可执行动作。',
    papers: [
      {
        id: '2302.00111',
        shortTitle: 'UniPi',
        title: 'Learning Universal Policies via Text-Guided Video Generation',
        year: 2023,
        relation: 'WAM 前置脉络',
        coupling: '级联生成',
        substrate: '像素未来',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2302.00111',
      },
      {
        id: '2310.08576',
        shortTitle: 'AVDC',
        title: 'Learning to Act from Actionless Videos through Dense Correspondences',
        year: 2023,
        relation: 'WAM 前置脉络',
        coupling: '级联几何提取',
        substrate: '像素与稠密对应',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2310.08576',
      },
      {
        id: '2310.10625',
        shortTitle: 'VLP',
        title: 'Video Language Planning',
        year: 2023,
        relation: 'WAM 前置脉络',
        coupling: '级联规划',
        substrate: '像素未来',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2310.10625',
      },
      {
        id: '2406.16862',
        shortTitle: 'Dreamitate',
        title: 'Dreamitate: Real-World Visuomotor Policy Learning via Video Generation',
        year: 2024,
        relation: 'WAM 前置脉络',
        coupling: '级联几何提取',
        substrate: '像素未来',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2406.16862',
      },
      {
        id: '2407.15208',
        shortTitle: 'Im2Flow2Act',
        title: 'Flow as the Cross-Domain Manipulation Interface',
        year: 2024,
        relation: 'WAM 前置脉络',
        coupling: '级联光流',
        substrate: '光流',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2407.15208',
      },
    ],
  },
  {
    id: 'joint',
    index: '03',
    title: '联合视频—动作建模',
    description: '视频未来与动作共享生成过程或联合表征，是 WAM 从前置脉络走向核心定义的关键路线。',
    papers: [
      {
        id: '2312.13139',
        shortTitle: 'GR-1',
        title: 'Unleashing Large-Scale Video Generative Pre-training for Visual Robot Manipulation',
        year: 2023,
        relation: 'WAM 前置脉络',
        coupling: '联合自回归',
        substrate: '像素潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2312.13139',
      },
      {
        id: '2411.18179',
        shortTitle: 'PAD',
        title: 'Prediction with Action: Visual Policy Learning via Joint Denoising Process',
        year: 2024,
        relation: 'WAM 前置脉络',
        coupling: '联合扩散',
        substrate: '像素潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2411.18179',
      },
      {
        id: '2504.02792',
        shortTitle: 'UWM',
        title: 'Unified World Models: Coupling Video and Action Diffusion for Pretraining on Large Robotic Datasets',
        year: 2025,
        relation: 'WAM 核心',
        coupling: '联合扩散',
        substrate: '像素潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2504.02792',
      },
      {
        id: '2506.21539',
        shortTitle: 'WorldVLA',
        title: 'WorldVLA: Towards Autoregressive Action World Model',
        year: 2025,
        relation: 'WAM 核心',
        coupling: '联合自回归',
        substrate: '像素潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2506.21539',
      },
      {
        id: '2602.15922',
        shortTitle: 'DreamZero',
        title: 'World Action Models are Zero-shot Policies',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '联合视频—动作扩散',
        substrate: '像素潜变量',
        status: '已精读',
        paperUrl: 'https://arxiv.org/abs/2602.15922',
        detailUrl: '/wam/papers/dreamzero/',
      },
    ],
  },
  {
    id: 'frontier',
    index: '04',
    title: '效率、价值与潜空间前沿',
    description: '追踪 2026 年以来对联合建模、隐式规划、潜空间预测和推理效率的探索。',
    papers: [
      {
        id: '2601.16163',
        shortTitle: 'Cosmos Policy',
        title: 'Cosmos Policy: Fine-Tuning Video Models for Visuomotor Control and Planning',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '联合扩散与规划',
        substrate: '帧潜变量与价值',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2601.16163',
      },
      {
        id: '2601.21998',
        shortTitle: 'LingBot-VA',
        title: 'Causal World Modeling for Robot Control',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '自回归—扩散联合',
        substrate: '视觉—动作共享潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2601.21998',
      },
      {
        id: '2602.10098',
        shortTitle: 'VLA-JEPA',
        title: 'VLA-JEPA: Enhancing Vision-Language-Action Model with Latent World Model',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '辅助潜变量预测',
        substrate: 'JEPA 潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2602.10098',
      },
      {
        id: '2603.16666',
        shortTitle: 'Fast-WAM',
        title: 'Fast-WAM: Do World Action Models Need Test-time Future Imagination?',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '训练期视频共训',
        substrate: '潜变量',
        status: '已精读',
        paperUrl: 'https://arxiv.org/abs/2603.16666',
        detailUrl: '/wam/papers/fast-wam/',
      },
      {
        id: '2604.14732',
        shortTitle: 'WAV',
        title: 'World-Value-Action Model: Implicit Planning for Vision-Language-Action Systems',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '世界—价值—动作联合',
        substrate: '轨迹潜变量与价值',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2604.14732',
      },
      {
        id: '2606.01027',
        shortTitle: 'τ0-WM',
        title: 'tau_0-WM: A Unified Video-Action World Model for Robotic Manipulation',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '策略—模拟器联合',
        substrate: '多视角视频潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2606.01027',
      },
      {
        id: '2606.05254',
        shortTitle: 'Flash-WAM',
        title: 'Flash-WAM: Modality-Aware Distillation for World Action Models',
        year: 2026,
        relation: 'WAM 核心',
        coupling: '蒸馏联合扩散',
        substrate: '视频—动作潜变量',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2606.05254',
      },
    ],
  },
  {
    id: 'surveys',
    index: '05',
    title: '综述与教程',
    description: '用不同综述视角检查定义、分类和遗漏；它们是导航入口，不替代原论文。',
    papers: [
      {
        id: '2605.00080',
        shortTitle: 'World Model for Robot Learning',
        title: 'World Model for Robot Learning: A Comprehensive Survey',
        year: 2026,
        relation: '综述',
        coupling: '不适用',
        substrate: '不适用',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2605.00080',
      },
      {
        id: '2605.12090',
        shortTitle: 'The Next Frontier',
        title: 'World Action Models: The Next Frontier in Embodied AI',
        year: 2026,
        relation: '综述',
        coupling: '不适用',
        substrate: '不适用',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2605.12090',
      },
      {
        id: '2606.20781',
        shortTitle: 'WAM Survey',
        title: 'World Action Models: A Survey',
        year: 2026,
        relation: '综述',
        coupling: '不适用',
        substrate: '不适用',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2606.20781',
      },
      {
        id: '2607.00836',
        shortTitle: 'Concise Tutorial',
        title: 'From World Models to World Action Models: A Concise Tutorial for Robotics',
        year: 2026,
        relation: '教程',
        coupling: '不适用',
        substrate: '不适用',
        status: '元数据已核验',
        paperUrl: 'https://arxiv.org/abs/2607.00836',
      },
    ],
  },
];

export const catalogPaperCount = catalogGroups.reduce((sum, group) => sum + group.papers.length, 0);
export const catalogReviewedCount = catalogGroups.reduce(
  (sum, group) => sum + group.papers.filter((paper) => paper.status === '已精读').length,
  0,
);
